### ISSUE TITLE
Doesn't integrate alongside Angular

### ISSUE THREAD

**Issue by Thorpe89** [rtfpessoa/diff2html#129]
I'm trying to run this plugin within an Angular app, I've having no luck due to a conflict with `$`.

The error I'm getting is:

`TypeError: $ is not a function at Diff2HtmlUI._initSelection at new Diff2HtmlUI`

We run noconflict and use `jq` in other places, had no issues with other plugins but this one just doesn't seem happy. I've searched but no one else seems to have had this issue?

There's a more in depth post here:
https://stackoverflow.com/questions/43808805/run-jquery-plugin-diff2html-inside-an-angular-directive

**Comment by rtfpessoa** [comment]
Seems like you already have some clues in stackoverflow.

You can also use diff2html directly instead of using the diff2html-ui helper, as described in the api here: https://github.com/rtfpessoa/diff2html#api. This way you can separate the html generation and insertion in the dom. But you will also have to bind the expandable files, side scroll and highlight separately.

Let me know if you need more help.

**Comment by Thorpe89** [comment]
I'm completely lost, the API examples don't seem to explain anything and `docs/diff2html.d.ts` doesn't exist? Are there any code examples without using the UI helper?

**Comment by rtfpessoa** [comment]
I just fixed the typescript definition location. It is actually in `typescript/diff2html.d.ts`, but if you are using typescript I am definitely not the right person to help you since I never actually used it. But from my understanding it is just like normal js after you include the definition, which is also included in the https://github.com/DefinitelyTyped/DefinitelyTyped repo.

About the library you just need to drop the dependencies and then call the `getPrettyHtml` and you will receive the HTML to insert where you want. Not sure what you mean by no docs, but as you can see its described in https://github.com/rtfpessoa/diff2html#api no need for anything else.

The demo page code is here https://github.com/rtfpessoa/diff2html/blob/master/website/templates/pages/demo/demo.js#L166 but it does some more logic with the inputs in the top so the highlighted line is where you want to look.

If you want code highlight and the other js tricks you just need to follow the instructions on the README and use the diff2html-ui helper. But as you already noticed it needs jQuery available globally.
If you want to do it yourself with your own stuff you have all the code for the diff2html-ui https://github.com/rtfpessoa/diff2html/blob/master/src/ui/js/diff2html-ui.js, notice it depends on some highlight-js functions that I copied to the file next to diff2html-ui.js, since we need some advanced stuff to allow partial highlight correctly.

If you go to https://diff2html.xyz/ in the end of the main page you have a section called `Projects using diff2html` where you can find a bunch of examples using it.
