### ISSUE TITLE
Including the commit message, hash, author etc. in the output

### ISSUE THREAD

**Issue by gonogo** [rtfpessoa/diff2html#152]
Hi,

When rendering a diff, I'd like to include the git commit message and the author. I can't see any examples of how to do this.

Is this possible?

Thanks!

**Comment by pbu88** [comment]
I've thought about this, which is a nice to have but in fact it falls out of the scope of the tool per se. Commit info is not part of a diff, is part of a commit (which incidentally has a diff as part of it).

In the case when a commit output is read by the tool, it would be possible to parse the commit info as well and provide it in the output object. When is just a plain diff, we don't do any of this.

Just some thoughts.

**Comment by rtfpessoa** [comment]
I completely forgot to answer this issue, sorry for the delay.

I completely agree with @pbu88. Having more information about the commit is kind of out of scope but would be nice to have. If you have any suggestion about how to do it let me know.

**Comment by dotnwat** [comment]
I was just about to hack on this feature when I stumbled across this ticket. I'd be happy to tackle this, if it is still in scope for the project.

From the standpoint of having a focused tool, I definitely agree that the scope should be limited to the diff. However, like it or not, nowadays the output of `git show` (which includes some basic metadata like commit message and author before the diff content) feels like its become its own standard.

My proposal for this ticket would be simply to add a header field to the DiffFile type. Rather than trying (yet) to parse the commit message and author etc... it would be useful to have just the content at the beginning of a file that the parser normally skips over.

Thoughts @rtfpessoa

**Comment by rtfpessoa** [comment]
@dotnwat I tough a bit about this and I have some concerns about that approach. I feel it is not very useful since you not actually parsing the data.

To make the cost of a new entity we should have some clear value in that information.

Some notes of what I have in mind:
* We definitely could create some new parser, that would parse the output of git show
  * If we would do this it would be important to support the basic functionality like multiples commits in same output (e.g.: `git show branch1 branch2` )
* We could delegate the parsing of the diff to the existing parser
  * We should avoid adding more complexity to the existing parser
* Would be cool to start with some use/test cases

What do you think?
