### ISSUE TITLE
Offset is in the wrong column

### ISSUE THREAD

**Issue by mrfyda** [rtfpessoa/diff2html#19]
![screen shot 2015-08-10 at 08 54 37](https://cloud.githubusercontent.com/assets/593860/9162379/862c8000-3f3d-11e5-8948-57fd9fbdd2a0.png)

**Comment by rtfpessoa** [comment]
If by offset you mean `@@ -38,7 +45,7 @@` that is kind of a feature.
Since it is returned in the middle of the diff I never tried to change it's position.

The first columns are the line numbers, I'm not sure if the offset would got well there.
Any suggestion? Can you provide an example of an improvement?

**Comment by pbu88** [comment]
I don't think this issue stands anymore. I never really saw the issue here and is pretty much what Github does. Unless de OP provides more context I think this could be closed.
