### ISSUE TITLE
Allow to have more context lines in the diffs

### ISSUE THREAD

**Issue by sabi0** [rtfpessoa/diff2html#207]
Diffs are produced with 3 context lines by default. Sometimes that's not enough for understanding the nature of the change (e.g. to see which method was changed).

It would be nice if diff2html allowed specifying custom number of context lines to render more detailed diffs.

It seems Bitbucket has it in the API directly with the `context` query parameter:
https://developer.atlassian.com/bitbucket/api/2/reference/resource/repositories/%7Busername%7D/%7Brepo_slug%7D/diff/%7Bspec%7D

GitHub should have something like this too. At least they do provide a way to access more context lines: https://github.blog/2013-12-02-expanding-context-in-diffs/

If possible it would also be nice to have an option for "Show full file content".

**Comment by rtfpessoa** [comment]
Since diff2html is just a parser and html generator it does not have a way to get more context.

To achieve this you just have to generate the diff with more context and then pass it to diff2html.

If you are referring to https://github.com/rtfpessoa/diff2html-cli, since it uses git below you can pass the git flag to request more context after ‘--’.
