### ISSUE TITLE
ability to render custom DOM content between lines 

### ISSUE THREAD

**Issue by svilenkov** [rtfpessoa/diff2html#239]
@rtfpessoa As per your [comment](https://github.com/rtfpessoa/diff2html/pull/238#issuecomment-539550766)
I'm considering using diff2html in our product that in itself has a manual code reviewing tool based on diff patches. diff2html covers almost all of our needs, however we would like to implement some additional functionality, so anyhow my plan is to implement it in a fork if it's not necessarily accepted to be an official feature of diff2html.

1) I wanna make it possible to insert custom DOM between lines which would eg. allow commenting lines of code and basically any kind of other content.
![image](https://user-images.githubusercontent.com/789427/66468955-49bb3180-ea87-11e9-8af5-6074e6ac9562.png)

2) Ability to customize the gutter, primarily for these purposes:
- adding buttons for dynamic loading of up/down lines around the diffed area like on github. 
[https://prnt.sc/pgu49z](https://prnt.sc/pgu49z)
![image](https://user-images.githubusercontent.com/789427/66468871-2c866300-ea87-11e9-86e5-fb129c2b8d29.png)
This would however mean implementing a separate functionality for inserting additional lines of code at arbitrary line numbers.

- adding buttons for other custom functionalities related to individual lines of code
[
![image](https://user-images.githubusercontent.com/789427/66468818-14aedf00-ea87-11e9-9698-bf1ecb32806b.png)
](url)

**Comment by rtfpessoa** [comment]
@svilenkov today diff2html is a kind of simple library to generate a static HTML from a unified/git diff.
The process is just about input and output.
We have a custom dom manipulation inside the diff2html-ui which does, highlight and other JS things.

With the model currently in the code it is hard to use this in react or in a more modular way like you seem to need.

I am open to think about this.

Would be nice if you could look at the code, get an idea on how you think it would be nice to implement and then describe it here. I will also take some time to think a bit more since mostly I delayed going this way.

**Comment by chimisu** [comment]
@rtfpessoa does this feature be supported now?

**Comment by rtfpessoa** [comment]
@chimisu nothing move here

**Comment by rtfpessoa** [comment]
@chimisu, I do not have any plans for new features atm.
If you are interested in contributing the work we can re-open this discussion and I can help you drive the idea.
