### ISSUE TITLE
Release version layout

### ISSUE THREAD

**Issue by pebbles186** [rtfpessoa/diff2html#293]
Hey,

starting with version 3.0.0 the release version does not follow the semantic versioning anymore.
For example in npm the latest version is 3.0.0-master.128204d
Is this intended or can you fix it, to have back the semantic versioning?

![grafik](https://user-images.githubusercontent.com/33489439/72248263-0aa4fb00-35f7-11ea-9291-89f8bfa67e60.png)

**Comment by rtfpessoa** [comment]
Hi @pebbles186,
The idea behind this versioning is to allow pre-releases as defined in https://semver.org/.
This means that this version is prior to 3.0.0 to allow for some wider experimentation while I finish the big update.

I guess the mistake was releasing this as `latest` tag since it is probably used by npm by default, but it happened while I was tweaking the build process.

Now that you know the reasons does this make sense?

**Comment by pebbles186** [comment]
Hi @rtfpessoa,
yes makes perfect sense :)
Thanks for the quick response.
