### ISSUE TITLE
Types are missing in the Diff2HtmlConfig interface

### ISSUE THREAD

**Issue by re2005** [rtfpessoa/diff2html#300]
Running the latest version.

In your example there are a few optional parameters:

```
Diff2Html.html(this.diffs, {
        drawFileList: true,
        matching: 'lines',
        outputFormat: 'side-by-side',
});

```

But the types are missing for these in the interface 'Diff2HtmlConfig'.

I've manually added (fileListToggle and matching) so my typescript doesn't complain.

fileListToggle?: boolean;
matching?: string;

**Comment by rtfpessoa** [comment]
@re2005 not sure if I completely get your point, but I think you might be mixing some concepts here.

As explained better in the new README specially in the branch where I will do the final release, there is Diff2Html (parser and html generator) and Diff2HtmlUI (wrapper around the previous to render stuff in the browser).

In this case `fileListToggle` is a config from Diff2HtmlUI and not Diff2Html it is optional and it has a default of true so there is no reason for you to have to worry about it.

Regarding `matching` it is in fact a parameter from Diff2Html but it is also optional and has a default of none.

Can you provide more details on what you are doing and how to replicate the issue? The information you provided is very short for me to be able to help.

**Comment by re2005** [comment]
Hi Pessoa, Thanks for the quick reply.
In my case I'm using **Diff2Html**.

My need is to set the fileListToggle to FALSE.

The VUE component has this code:

```
get prettyHtml() {
    return Diff2Html.html(this.status.diff, {
        fileListToggle: false,
        drawFileList: false
    });
}
```

> TS2345: Argument of type '{ fileListToggle: boolean; drawFileList: false; }' is not assignable to parameter of type 'Diff2HtmlConfig'.   Object literal may only specify known properties, and 'fileListToggle' does not exist in type 'Diff2HtmlConfig'.

The example was from here:
https://github.com/rtfpessoa/diff2html#diff2html-vuejs-example

And my bad because the option 'fileListToggle' is not in the example.

Anyway it's still a valid case right ?

Cheers

**Comment by re2005** [comment]
And I can't forget to say: very good job with this repo!

**Comment by rtfpessoa** [comment]
@re2005 I think I got what is wrong.

The problem here seems to be that you are trying to use a feature of Diff2HtmlUI which is the `fileListToggle`. If you are using Diff2Html with Vue you can only decide if you want the list or not by passing the `drawFileList` parameter.

You can check all the [Diff2Html options](https://github.com/rtfpessoa/diff2html/tree/release-major-version#diff2html-configuration) and the [Diff2HtmlUI extra options](https://github.com/rtfpessoa/diff2html/tree/release-major-version#diff2htmlui-configuration)

If you really want that feature you can use Diff2HtmlUI, but since it does changes in the DOM you might want to say to Vue that this part of the DOM is uncontrolled. (I think this is available in React, not sure about Vue)

Does this answer your problem?

**Comment by re2005** [comment]
You're totally right. In fact that option is already there.

Thanks a lot man!
