### ISSUE TITLE
support for diff json from gitlab api

### ISSUE THREAD

**Issue by devajith** [rtfpessoa/diff2html#333]
how can we use [gitlab-diff-of-a-commit](https://docs.gitlab.com/ee/api/commits.html#get-the-diff-of-a-commit) api with diff2html ?

**Comment by devajith** [comment]
its looks like gitlab api having a [bug](https://gitlab.com/gitlab-org/gitlab/-/issues/24913) for not showing 'diff' properly otherwise we would have use 'diff' directly.

**Comment by rtfpessoa** [comment]
Hi @devajith,

diff2html is a diff parser and html generator and for that reason it does not support that API. It only supports unified diff formats or supersets of it.

Since that API has a json version that is specific to GitLab it is of no use here.

From GitLab you can get the diff from `https://gitlab.com/gitlab-org/gitlab-foss/-/merge_requests/6763.diff` for a mege request.
