### ISSUE TITLE
Endless diffing upon relatively small git diff payload with HTML output

### ISSUE THREAD

**Issue by mensfeld** [rtfpessoa/diff2html#415]
### Step -1: Before filing an issue check out the troubleshooting section

- Done

### Step 0: Describe your environment

- OS: `Ubuntu 20.04`
- diff2html version: `5.1.11` cli and `3.4.11` diff2html
- Using diff2html directly or using diff2html-ui helper: directly
- Extra flags: `--matching none`

#### Steps to reproduce:

1. `curl https://gist.githubusercontent.com/mensfeld/4711d1a697ce0dbf1b0fecac4da1b67d/raw/751b28ae26e8961398a369290010366fd651cb3b/base.diff > base.diff`
2. `yarn run diff2html --matching none -i file -o stdout base.diff`
3. Wait forever

Update: when running with `json` as the format, finishes fast

#### diff example:

https://gist.githubusercontent.com/mensfeld/4711d1a697ce0dbf1b0fecac4da1b67d/raw/751b28ae26e8961398a369290010366fd651cb3b/base.diff

#### Observed Results:

Runs forever with 100%  CPU

#### Expected Results:

Since the base diff ain't that big, I would expect it to finish.

**Comment by rtfpessoa** [comment]
Hello @mensfeld, that issue is regarding the cli in the [other repository](https://github.com/rtfpessoa/diff2html-cli).

The problem seems to be the huge line length.
You can fix it by reducing the `maxLineLengthHighlight` but rn it is not possible to do that in the CLI. 

Feel free to send a PR to add the flag, I can do it but I need to find some time.

You can see it working here https://diff2html.xyz/demo.html?matching=none&matchWordsThreshold=0.25&maxLineLengthHighlight=1000&diffStyle=word&renderNothingWhenEmpty=0&matchingMaxComparisons=2500&maxLineSizeInBlockForComparison=200&outputFormat=line-by-line&drawFileList=1&synchronisedScroll=1&highlight=1&fileListToggle=1&fileListStartVisible=0&smartSelection=1&fileContentToggle=1&diff=https://gist.githubusercontent.com/mensfeld/4711d1a697ce0dbf1b0fecac4da1b67d/raw/751b28ae26e8961398a369290010366fd651cb3b/base.diff

**Comment by mensfeld** [comment]
Thank you for the clarification. I can try exposing this option but to be honest my JS knowledge is pretty limited :(

If I can I will submit a PR, otherwise I will wait for your help :pray:

**Comment by mensfeld** [comment]
Thank you :pray:
