### ISSUE TITLE
Question: Is there an option to output the entire resulting file?

### ISSUE THREAD

**Issue by krisnye** [rtfpessoa/diff2html#417]
I want all of the diffs as they are shown, but I also want to see the entire content of the resulting file.

Is there an option for that?

If not, can someone add that or would you accept a PR which added it?

**Comment by rtfpessoa** [comment]
> I want all of the diffs as they are shown, but I also want to see the entire content of the resulting file.
> Is there an option for that?
> If not, can someone add that or would you accept a PR which added it?

You can check this issue here https://github.com/rtfpessoa/diff2html/issues/406

TLDR, this is a parser and html generator, it only generates what it receives and the lines which you are asking for are not being passed to the tool. You can ask `git` or whatever tool you are using to give you more context lines.

Let me know if this makes sense.

**Comment by rtfpessoa** [comment]
> Hmmm...it takes about 15 minutes to figure out that diff2html does not generate the diff itself. IMO there're two ways to improve the situation:

Not sure I understand why it would take so long. In the first line of the Readme I mention:

> diff2html generates pretty HTML diffs from git diff or unified diff output.

I even say where the diff is supposed to come from.

Feel free to send a PR improving the README.
