### ISSUE TITLE
[Question] How do you use the UI Helper without <script> imports?

### ISSUE THREAD

**Issue by stephendolan** [rtfpessoa/diff2html#422]
This is more of a question than an actual suspected bug, so I'm omitting some of this template.

### Step 0: Describe your environment

- OS: macOS 12.1
- diff2html version: 3.4.14
- Using diff2html directly or using diff2html-ui helper: Trying to use helper
- Extra flags: None

### Step 1: Describe the problem:

I'm currently using the plain Diff2HTML export to consume and display diffs, and it works beautifully. However, I'd love to switch to the UI helper.

I'm unable to figure out how to import the Diff2HTMLUi module noted in the examples for usage in TypeScript. Everything seems to assume imports via `<script>` tags in the current docs - is there a way to do something like `import { Diff2HTMLUi } from "diff2html";` that pulls in TypeScript definitions and makes the module available?

I'll _happily_ submit a PR to the README once I understand how to tackle this!

#### Relevant Code:

Trying to convert this code to use Diff2HTML UI instead, but I can't find an `import` statement that will work:
https://github.com/stephendolan/lucky_diff/blob/main/src/js/controllers/diff_to_html_controller.ts

**Comment by rtfpessoa** [comment]
Hello 👋,

I guess I could make that more obvious in the readme.
You can see an example https://github.com/rtfpessoa/diff2html/blob/master/website/templates/pages/demo/demo.ts#L1

In the README you have a [Distributions](https://github.com/rtfpessoa/diff2html#distributions) and a bullet point `NPM / Node.js library` you have all the importable node module paths and a quick explanation of each of them.
This includes the `lib/ui/js/diff2html-ui-slim.js` used in the example above. Notice the `../../../../src/` to `lib/` difference since this is local code to the project. In your case you should use the same written in the README.

Does this make sense?

**Comment by stephendolan** [comment]
This was helpful, though I had to do a bit of cross-referencing to figure everything out! Here's what I ended up needing to do for a TypeScript StimulusJS controller to render the Diff2HTML UI output, in case it's helpful to anyone in the future:

```typescript
import { Controller } from "@hotwired/stimulus";

import {
  Diff2HtmlUI,
  Diff2HtmlUIConfig,
} from "diff2html/lib/ui/js/diff2html-ui-slim.js";

export default class extends Controller {
  connect(): void {
    const diff2htmlUi = new Diff2HtmlUI(
      this.diffElement,
      this.unifiedDiff,
      this.diffConfiguration
    );

    diff2htmlUi.draw();
  }

  get unifiedDiff(): string {
    return this.data.get("unifiedDiff") || "";
  }

  get diffElement(): HTMLElement {
    return this.element as HTMLElement;
  }

  get diffConfiguration(): Diff2HtmlUIConfig {
    return {
      drawFileList: true,
      matching: "lines",
    };
  }
}
```

**Comment by rtfpessoa** [comment]
Added that example to the readme. thanks
