### ISSUE TITLE
[Question] About nodeStream and mergeStream

### ISSUE THREAD

**Issue by ricenoddle** [rtfpessoa/diff2html#424]
Hello there, 
Nowadays I'm looking for your code trying to do some custom operations and I find that you have nodeStream and mergeStream to provide the context for highlightjs. Let me first describe what I'm doing now

 In the following screenshot, I have implemented a fold function. But there is a situation that when my comment code is end in the folded code, it will make all my rest code not highlighted correctly.
![image](https://user-images.githubusercontent.com/13479751/150906720-69232549-1f77-48dc-a8b6-7360aef5829f.png)

By looking through your code, I find there are two functions `nodeStream` and `mergeStream` that may help me to solve this problem. But I'm a little bit confused about how you get the context. I'm now trying to split my code and rehighlight it, but I find the `comment status` will followed. Is there a way for me to use `mergeStream` to reset the status to my code ?

**Comment by rtfpessoa** [comment]
I do not think this is fixable. Since you do not have enough context. You need to ask git to give you more context lines when you generate the diff.

There is a discussion here https://github.com/rtfpessoa/diff2html/issues/392#issuecomment-855188212 which is from a different problem. The problem there we fixed but the issue with partial code is still there.
